title: Coaching journal
description: An agile odyssey - Immersive journal of transformative lessons
theme: just-the-docs

url: https:/riteshmehrotra.github.io/coaching-journal


nav_sort: case_sensitive

search_enabled: true

layout: default
has_children: true


plugins:
  - jemoji