title: Coaching journal
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https:/riteshmehrotra.github.io/coaching-journal


nav_sort: case_sensitive

search_enabled: true

layout: default
has_children: true


plugins:
  - jemoji